### ISSUE TITLE
Build failure with aeson 0.10

### ISSUE THREAD

**Issue by bergmark** [wereHamster/avers-haskell#1] opened 2015-12-18 17:39 UTC
```
src/Avers/Types.hs:249:3:
    Couldn't match expected type ‘Text’
                with actual type ‘Data.ByteString.Builder.Internal.Builder’
    In the first argument of ‘(Aeson..=)’, namely
      ‘aeson-0.10.0.0:Data.Aeson.Encode.Builder.text (T.pack "value")’
    In the first argument of ‘(<$>)’, namely
      ‘(aeson-0.10.0.0:Data.Aeson.Encode.Builder.text (T.pack "value")
        Aeson..=)’
```

Also see: http://matrix.hackage.haskell.org/package/avers#GHC-7.10/avers-0.0.12

Stackage* just upgraded to aeson-0.10 which means I need to disable avers for now. Please send a pull request to re-enable it when this is fixed. If this happens before new years avers will still be included in LTS 4.

**Comment by wereHamster** [comment] 2015-12-18 18:40
This is a bug in aeson. I suggest pulling 0.10.0.0 of aeson from stackage instead. https://github.com/bos/aeson/issues/293. The bug was fixed on Oct 10, 2015 but no new release of aeson was made since.

**Comment by wereHamster** [comment] 2015-12-18 18:51
Aeson still has so many bugs open which were caused by the 0.10 release that I'm surprised that stackage decided to go ahead with the upgrade.

**Comment by bergmark** [comment] 2015-12-18 19:22
We stackage curators decided to clean up old tickets and also specifically discussed aeson. I was aware of some semantic changes but not  of any serious bugs. The stackage issue has been open for three months without any mentions of this.

I see that bos/aeson#293 is at least fixed on github, would releasing that be enough for avers? I'll open an aeson issue and check the status.

**Comment by bergmark** [comment] 2015-12-18 19:30
https://github.com/bos/aeson/issues/328

**Comment by wereHamster** [comment] 2015-12-18 19:39
The stackage issue, it's been open for months but you never decided to actually try to build all the packages against the newer aeson version and see what breaks? Isn't that the whole point of stackage, to tell me that my package breaks before it actually matters?

Also, matrix.hackage.haskell.org doesn't actively send out emails or tries to reach out to me, so I was never aware of the problem.

**Comment by bergmark** [comment] 2015-12-18 20:10
The current strategy we use is to not ignore upper bounds on other packages, which means that someone not having upper bounds will get a notification only when all the upper bounds have been relaxed. 

Another strategy could be to build everything with `--allow-newer`. This could help but it could also make everything worse. If some package with reverse dependencies actually breaks everyone depending on it will be in the dark about updates to **all** their dependencies until this (and all of their other dependencies) have been updated.

Depending on how much extra work it is, we could try to close issues pre-emptively after every N days of waiting to see if problems with other packages arise. 

We can also be more aggressive about forcing upgrades, this would still mean that your package would have gotten excluded from nightly, but at least you'd be notified much sooner.

I'll ask the other curators for their thoughts on this.

**Comment by bergmark** [comment] 2015-12-18 20:25
And i should add, matrix is very much in an experimental stage so it cannot notify people in a timely fashion. Would be awesome to add RSS for authors to complement packdeps.

**Comment by wereHamster** [comment] 2016-02-28 11:05
Aeson 0.10 is deprecated so I'm closing this one. Avers builds with both 0.9 and 0.11.

**Closed by wereHamster** 2016-02-28 11:05 UTC
